export * from './BorderedContainer';
export * from './ColoredContainer';
export * from './FormContainer';
export * from './GrayBox';
export * from './MainContainer';
export * from './MainContainer2';
export * from './OutlinedDiv';
export * from './Overlay';
export * from './WhiteBox';
