import { z } from 'zod';

export const andpadProjTypes = ['リフォーム', '新築', 'リノベーション', 'エクステリア', 'アフター', '分譲', '注文', 'その他'] as const;
export type AndpadProjType = typeof andpadProjTypes[number];

export const andpadProjFlow = ['契約前', '着工前', '進行中', '完工（精算前）', '精算完了', '失注'] as const;
export type AndpadProjFlow = typeof andpadProjFlow[number];

export const andpadOrderSchema = z.object({
  data: z.object({
    object: z.object({
      'システムID': z.number(),
      '案件管理ID': z.string(),
      '案件名': z.string(),
      '案件種別': z.enum(andpadProjTypes),
      '顧客ID': z.number(),
      '顧客管理ID': z.string(),
      '物件ID': z.number(),
      '物件管理ID': z.string(),
      '案件フロー': z.enum(andpadProjFlow).optional(),
      '案件備考': z.string().optional(),
      'その他': z.string().optional(),
      'キーBOX': z.string().optional(),
      '集合ポスト': z.string().optional(),
      '養生範囲（共用部）': z.string().optional(),
      '遮音規制（選択）': z.string().optional(),
      '遮音規制': z.string().optional(),
      'スリーブ穴あけ可否（選択）': z.string().optional(),
      'スリーブ穴あけ可否': z.string().optional(),
      'インターホン交換': z.string().optional(),
      '専有部消火器': z.string().optional(),
      '自火報工事の有無/指定業者': z.string().optional(),
      '挨拶不在者（選択）': z.string().optional(),
      '挨拶不在者': z.string().optional(),
      '{マイルストーン名}(予定)': z.string().optional(),
      '{マイルストーン名}(実績)': z.string().optional(),
      '役割:設計': z.string().optional(),
      '役割:工事': z.string().optional(),
      '役割:営業': z.string().optional(),
      '役割:{役割名}': z.string().optional(),
      'ラベル:{ラベル名}': z.string().optional(),
      '{セクション名}:{項目名}': z.string().optional(),
      '種別': z.string().optional(),
      '顧客名': z.string().optional(),
      '顧客名（カナ）': z.string().optional(),
      '顧客郵便番号': z.string().optional(),
      '顧客都道府県': z.string().optional(),
      '顧客現住所': z.string().optional(),
      '顧客緯度': z.string().optional(),
      '顧客経度': z.string().optional(),
      '顧客担当者名': z.string().optional(),
      '顧客担当者名（カナ）': z.string().optional(),
      '顧客電話番号1': z.string().optional(),
      '顧客電話番号2': z.string().optional(),
      '顧客メールアドレス': z.string().optional(),
      '顧客FAX': z.string().optional(),
      '性別': z.string().optional(),
      '生年月日': z.string().optional(),
      '顧客備考': z.string().optional(),
      '顧客情報任意項目:{顧客情報任意項目名}': z.string().optional(),
      '物件種別': z.string().optional(),
      '物件名': z.string().optional(),
      '物件名（カナ）': z.string().optional(),
      '号室': z.string().optional(),
      '物件住所種別': z.string().optional(),
      '物件郵便番号': z.string().optional(),
      '物件都道府県': z.string().optional(),
      '物件住所': z.string().optional(),
      '物件緯度': z.string().optional(),
      '物件経度': z.string().optional(),
      '物件電話番号': z.string().optional(),
      '交通アクセス': z.string().optional(),
      '築年月': z.string().optional(),
      '専有面積・延床面積': z.number().optional(),
      '間取り': z.string().optional(),
      '材質構造': z.string().optional(),
      '総戸数': z.number().optional(),
      '物件備考': z.string().optional(),
      '工事可能時間（選択）': z.string().optional(),
      '工事可能時間': z.string().optional(),
      '土曜日の工事（選択）': z.string().optional(),
      '土曜日の工事': z.string().optional(),
      '駐車スペース（選択）': z.string().optional(),
      '駐車スペース': z.string().optional(),
      'タバコ喫煙ルール（選択）': z.string().optional(),
      'タバコ喫煙ルール': z.string().optional(),
      '近隣承認（選択）': z.string().optional(),
      '近隣承認': z.string(),
      '近隣挨拶範囲（選択）': z.string().optional(),
      '近隣挨拶範囲': z.string().optional(),
      'エレベーター': z.string().optional(),
      'オートロック': z.string().optional(),
      '管理人名': z.string().optional(),
      '管理人TEL': z.string().optional(),
      '管理人FAX': z.string().optional(),
      '理事長名': z.string().optional(),
      '理事長TEL': z.string().optional(),
      '管理会社名': z.string().optional(),
      '管理会社担当名': z.string().optional(),
      '管理会社TEL': z.string().optional(),
      '管理会社FAX': z.string().optional(),
      '管理体制': z.string().optional(),
      '勤務時間': z.string().optional(),
      '物件情報任意項目:{物件情報任意項目名}': z.string().optional(),
    }),
  }),
});

export type TAndpadOrderResult = z.infer<typeof andpadOrderSchema>;
export type KAndpadOrderResult = keyof TAndpadOrderResult['data']['object'];