import { CustomerForm } from '../../form';

export const testData: CustomerForm =  {
  id: undefined,
  revision: '',
  store: '11',
  cocoAG1: '40',
  cocoAG2: '43',
  yumeAG1: '28',
  yumeAG2: '65',
  customers: [
    {
      key: '',
      id: '',
      revision: '',
      custName: 'てすと',
      isSameAddress: true,
      custNameReading: 'テスト',
      gender: '女性',
      birthYear: '1995',
      birthMonth: '6',
      birthDay: '11',
      postal: '441-8124',
      address1: '愛知県豊橋市野依町',
      address2: 'banchi1',
      phone1: '07014529634',
      phone1Rel: '祖父母',
      phone2: '',
      phone2Rel: '',
      email: 'lenzras@gmail.com',
      emailRel: '',
    },
    {
      key: '',
      id: '',
      revision: '',
      custName: 'てすと２',
      isSameAddress: false,
      custNameReading: 'テスト',
      gender: '女性',
      birthYear: '1995',
      birthMonth: '6',
      birthDay: '11',
      postal: '441-8134',
      address1: 'ててててて',
      address2: 'banchi2',
      phone1: '07014529634',
      phone1Rel: '祖父母',
      phone2: '',
      phone2Rel: '',
      email: 'lenzras@gmail.com',
      emailRel: '',
    },
  ],
} ;
